name: key-value-checker
version: '${version}'

main: org.kotsasmin.keyValueChecker.KeyValueChecker
api-version: '1.21'
load: POSTWORLD
softdepend: [packetevents]

commands:
  kvc-reload:
    description: Reloads the KeyValueChecker config
    permission: keyvaluechecker.reload
  kvc-list:
    description: Lists all players currently detected with mods
    permission: keyvaluechecker.list
  kvc-whitelist:
    description: Manages the player whitelist for bypassing checks
    permission: keyvaluechecker.whitelist

permissions:
  keyvaluechecker.reload:
    description: Allows reloading the KeyValueChecker configuration.
    default: op
  keyvaluechecker.list:
    description: Allows viewing the detected modifications history.
    default: op
  keyvaluechecker.notify:
    description: Allows admins to see in-game alerts when a player is detected with a disallowed mod.
    default: op
  keyvaluechecker.whitelist:
    description: Allows managing the player whitelist for bypassing checks.
    default: op

